### PR TITLE
Update Swift Version

### PR DESCRIPTION
**Pull request by iwill**

### CODE REVIEW

**Comment by simonmcl** [comment]
@zoul Can we get this checked / merged in please? its causing warnings in Xcode 13 for any app that imports it. Thanks

**Comment by zoul** [comment]
Sorry, I longer maintain this. I suggest you fork the code and fix the problem in your fork – or, if you were interested in maintaining it, I can transfer the repo to you?

Or, as a quick stop-gap measure, is it enough just to merge this?

**Comment by iwill** [comment]
@zoul Could you transfer this repo and the [pod](https://cocoapods.org/pods/GenericJSON) to me? I'm glad to maintain it.

**Comment by zoul** [comment]
Sure thing! I can’t transfer the repo now since `iwill/generic-json-swift` already exists, can you move it out of the way? And where / how can I transfer the pod? (Are CocoaPods still a thing?) Thank you!

**Comment by iwill** [comment]
That's great, thank you very much! I've removed `iwill/generic-json-swift`. You can [add my accout as an owner](https://guides.cocoapods.org/making/getting-setup-with-trunk#adding-other-people-as-contributors) with this command: `pod trunk add-owner GenericJSON m***@gmail.com`, and you can also see `pod trunk --help` for more.

**Comment by zoul** [comment]
Done! If you need some more help with the transfer, feel free to write here or at tomas.znamenacek@gmail.com. Thank you for taking the library over and good luck!

**Comment by iwill** [comment]
I will take care of it :smile:

**Comment by simonmcl** [comment]
@iwill can you also update `package.swift` to use the latest version of swift as well, thanks

**Comment by iwill** [comment]
@simonmcl I released a new version [GenericJSON-2.0.2](https://github.com/iwill/generic-json-swift/releases/tag/2.0.2), please have a try.

**Comment by simonmcl** [comment]
@iwill that fixed it, thank you!  finally back to zero warnings!

**Pull request closed without merging**
