### PR TITLE
Feature: Mutating accessors

### PR DESCRIPTION
**Pull request by cjmconie**
This PR aims to allow `JSON` types to be mutable after initialisation.

- I have added property setters and accompanying unit tests.
- Additionally, I have renamed the 'Querying' files as the name did not suit both setting and getting operations imo - though I'm very happy to change this to some other name.
- Unfortunately the renaming via Xcode broke the diff... I'm not sure if there is a way to rename and keep the diff?

Lastly, I am very happy to revise the PR (or close it if it does not make sense).

### CODE REVIEW

**Comment by zoul** [comment]
I like to rebase the branch on top of master and clean the history a bit (by squashing, for example) before submitting a PR, but that’s not the important part – the important part is that I like immutable data types and I would like the JSON value to stay immutable if possible. (There’s a lot of good resources on immutable data types online, tell me if you feel this point needs better justification.) What’s your use case for the inplace mutation? Is it essential for you to change the JSON value in place? If you really need to modify the JSON, could we come up with an immutable API?

**Comment by cjmconie** [comment]
OK, I will rebase onto master (to clean up the PR) and then investigate immutable data types and see where this PR can be improved (or even discarded).

The use case is fairly straight forward. Our server returns an JSON object which is decoded into a native swift struct, e.g. `SomeThing` (shown below). The `JSON` type is used for one of the properties as its json contents/structure are defined - but unknown at the time of decoding.

```swift
struct SomeThing: Decodable {
    var lastName: String
    var firstName: String
    var unknown: JSON
}
```

At this point an immutable data type meets the needs. 

However, our server also pushes *partial* state updates for the unknown `JSON` property. This means the `unknown` property must be updated (in our case a new JSON object must be merged in). I'm not sure how to achieve this without making `JSON` immutable via setters. 

Any suggestions?

**Comment by zoul** [comment]
> However, our server also pushes partial state updates for the unknown JSON property. This means the unknown property must be updated (in our case a new JSON object must be merged in). I'm not sure how to achieve this without making JSON immutable via setters.

Could we simply introduce some kind of `merging(with: JSON) -> JSON` function that would return a new value created by merging in the updates? Is it obvious how the function should behave?

**Comment by cjmconie** [comment]
Yes, that is definitely the better approach. A `merging(with:)` function would solve my use case and probably apply to many other use cases too.

**Comment by zoul** [comment]
So is it OK with you if I close this and create a new issue to discuss how the merge should work?

**Comment by cjmconie** [comment]
Yes, that's good with me.

**Pull request closed without merging**
